---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.dcaspi.dev
      recordType: CNAME
      targets:
        - 9f2639f7-b0ba-4e76-8f70-2a758e667f78.cfargotunnel.com
