apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - cloudflare-dns.yaml
  # - cloudflare-tunnel.yaml
  - dns-endpoint.yaml
  - external-secrets.yaml
  - gateway.yaml
