---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: external-secrets
spec:
  image: "ghcr.io/external-secrets/charts/external-secrets"
  interval: 12h
  provider: generic

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: external-secrets
spec:
  imageRepositoryRef:
    name: external-secrets
  policy:
    semver:
      range: ">=2.0.0"
