router bgp 65000
 bgp router-id 192.168.1.1
 ! Point to Kubernetes RK1 Node 1
 neighbor 192.168.2.144 remote-as 65001
 ! Point to Kubernetes RK1 Node 2
 neighbor 192.168.2.19 remote-as 65001
 !
 address-family ipv4 unicast
  ! Accept the routes Cilium advertises to the router
  neighbor 192.168.2.144 route-map ALLOW-ALL in
  neighbor 192.168.2.19 route-map ALLOW-ALL in
 exit-address-family
!
route-map ALLOW-ALL permit 10
