multitenancy:
  enabled: true
  defaultServiceAccount: flux-operator
reporting:
  interval: 45s
web:
  networkPolicy:
    create: false
  httpRoute:
    enabled: true
    parentRefs:
      - name: http-internal
        namespace: networking
    hostnames:
      - flux.dcaspi.dev
tolerations:
  - operator: Exists
